[irc]
owners = ["dbaron"]
nickname = "github-bot-dev"
alt_nicks = ["github-bot-dev-", "github-bot-dev--"]
username = "dbaron-gh-bot"
realname = "Bot to add meeting minutes to github issues."
server = "irc.w3.org"
port = 994
use_tls = true
encoding = "UTF-8"
user_info = "Bot to add meeting minutes to github issues."

[bot]
source = "https://github.com/dbaron/wgmeeting-github-ircbot"
github_uastring = "wgmeeting-github-ircbot/0.4.4"
activity_timeout_minutes = 90
owners = ["dbaron"]


[channels."#cssbottest"]
group = "github-bot testing Working Group"
github_repos_allowed = [
    "dbaron/wgmeeting-github-ircbot",
]
